import { sql } from "drizzle-orm";
import { migrationsDir } from "@congress/test-support";
import { beforeAll, beforeEach, describe, expect, it } from "vitest";
import { db, runMigrations } from "./db/client.js";
import { places, positions } from "./db/schema.js";
import { claimStrength, overlapMs } from "./annotationMatching.js";
import { healTrackingStateOnBoot, reprocessRange } from "./reprocess.js";
import { processPositions, resetTrackingState } from "./tracking.js";
import { classifyVisit, listTrips, listVisits } from "./visits.js";
import type { TraccarPosition } from "./traccar/client.js";

beforeAll(() => runMigrations(migrationsDir("chamber-map")));

beforeEach(() => {
  db.run(sql`delete from trips`);
  db.run(sql`delete from visits`);
  db.run(sql`delete from places`);
  db.run(sql`delete from positions`);
  resetTrackingState();
  nextFixId = 1;
});

describe("overlapMs", () => {
  it("measures the shared stretch of two spans", () => {
    expect(overlapMs({ start: 0, end: 100 }, { start: 50, end: 200 })).toBe(50);
  });

  it("is zero for disjoint spans", () => {
    expect(overlapMs({ start: 0, end: 100 }, { start: 200, end: 300 })).toBe(0);
  });

  it("is zero for spans that merely touch", () => {
    expect(overlapMs({ start: 0, end: 100 }, { start: 100, end: 200 })).toBe(0);
  });

  it("is the whole of the shorter span when one contains the other", () => {
    expect(overlapMs({ start: 50, end: 60 }, { start: 0, end: 100 })).toBe(10);
  });
});

describe("claimStrength", () => {
  // This is what decides whether a label the owner typed survives a history
  // rebuild or is silently lost.
  const saved = { start: 0, end: 100 };

  it("rejects an overlap below half the saved span", () => {
    expect(claimStrength(saved, { start: 60, end: 200 })).toBe(0);
  });

  it("accepts an overlap of exactly half, since the threshold is inclusive", () => {
    expect(claimStrength(saved, { start: 50, end: 200 })).toBe(50);
  });

  it("accepts a generous overlap and reports its size, so the best candidate can win", () => {
    expect(claimStrength(saved, { start: 0, end: 100 })).toBe(100);
    expect(claimStrength(saved, { start: 10, end: 100 })).toBe(90);
  });

  it("rejects a candidate that merely abuts the saved span", () => {
    expect(claimStrength(saved, { start: 100, end: 300 })).toBe(0);
  });

  it("rejects a disjoint candidate", () => {
    expect(claimStrength(saved, { start: 500, end: 600 })).toBe(0);
  });
});

// --- Replay ---

const T0 = Date.parse("2026-03-01T08:00:00.000Z");
const HOME_LAT = 45.0;
const WORK_LAT = 45.05;
let nextFixId = 1;

function fix(latitude: number, minuteOffset: number, reportedKnots = 0): TraccarPosition {
  return {
    id: nextFixId++,
    deviceId: 1,
    latitude,
    longitude: 9,
    speed: reportedKnots,
    fixTime: new Date(T0 + minuteOffset * 60_000).toISOString(),
    attributes: {},
  };
}

function place(name: string, latitude: number, radiusMeters = 100) {
  return db
    .insert(places)
    .values({ name, latitude, longitude: 9, radiusMeters, createdAt: new Date(), updatedAt: new Date() })
    .returning()
    .get();
}

// Ids are regenerated by a rebuild, so a before/after comparison has to be
// on what the record actually says rather than on row identity.
async function snapshot() {
  const visits = (await listVisits({})).map((v) => ({
    placeName: v.placeName,
    status: v.status,
    adhocLabel: v.adhocLabel,
    arrivedAt: v.arrivedAt,
    departedAt: v.departedAt,
  }));
  const trips = (await listTrips({})).map((t) => ({
    fromLabel: t.fromLabel,
    toLabel: t.toLabel,
    departedAt: t.departedAt,
    arrivedAt: t.arrivedAt,
    mode: t.mode,
    distanceKm: Number(t.distanceKm.toFixed(6)),
  }));
  return { visits, trips };
}

const COMMUTE = () => [fix(HOME_LAT, 0), fix(45.01, 1), fix(45.02, 2), fix(45.03, 3), fix(45.04, 4), fix(WORK_LAT, 5)];

const DWELL_THEN_WORK = () => [
  fix(HOME_LAT, 0),
  fix(45.01, 1),
  fix(45.025, 2),
  fix(45.025, 3),
  fix(45.025, 10),
  fix(45.0251, 20),
  fix(WORK_LAT, 30),
];

describe("reprocessRange", () => {
  it("reproduces an identical history when nothing has changed", async () => {
    // The invariant the whole rebuild rests on: visits and trips are derived
    // from the raw fix log, so replaying that log against unchanged places
    // and settings must land in exactly the same place.
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(COMMUTE(), { publishEvents: false });

    const before = await snapshot();
    await reprocessRange(new Date(T0));
    expect(await snapshot()).toEqual(before);
  });

  it("reproduces an identical history for a trace containing an unclassified dwell", async () => {
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(DWELL_THEN_WORK(), { publishEvents: false });

    const before = await snapshot();
    await reprocessRange(new Date(T0));
    expect(await snapshot()).toEqual(before);
  });

  it("reports what it deleted and recreated", async () => {
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(COMMUTE(), { publishEvents: false });

    const result = await reprocessRange(new Date(T0));
    expect(result).toMatchObject({
      positionsReplayed: 6,
      visitsDeleted: 2,
      visitsCreated: 2,
      tripsDeleted: 1,
      tripsCreated: 1,
    });
  });

  it("applies a place added after the fact to the history it should have matched", async () => {
    // The reason this machinery exists: a dwell the owner later names should
    // become an ordinary confirmed visit to that place across history, not
    // just going forward.
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(DWELL_THEN_WORK(), { publishEvents: false });
    expect((await listVisits({})).filter((v) => v.status === "pending")).toHaveLength(1);

    place("Gym", 45.025);
    await reprocessRange(new Date(T0));

    const visits = await listVisits({});
    expect(visits.filter((v) => v.status === "pending")).toHaveLength(0);
    expect(visits.map((v) => v.placeName)).toContain("Gym");
  });

  it("keeps a visit that was already underway before the replay window", async () => {
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(COMMUTE(), { publishEvents: false });

    // Start the rebuild after Home was left; Home itself must survive with
    // its own, earlier arrival intact.
    await reprocessRange(new Date(T0 + 60_000));

    const home = (await listVisits({})).find((v) => v.placeName === "Home");
    expect(home?.arrivedAt).toBe(new Date(T0).toISOString());
  });
});

describe("annotations across a rebuild", () => {
  async function dwellNamedAdhoc(label: string) {
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(DWELL_THEN_WORK(), { publishEvents: false });
    const pending = (await listVisits({})).find((v) => v.status === "pending")!;
    await classifyVisit(pending.id, { action: "adhoc_label", label });
    return pending;
  }

  it("carries a one-off label onto the regenerated dwell", async () => {
    await dwellNamedAdhoc("dentist");
    const result = await reprocessRange(new Date(T0));

    expect(result.annotationsRestored).toBeGreaterThanOrEqual(1);
    expect(result.annotationsLost).toBe(0);
    const restored = (await listVisits({})).find((v) => v.status === "adhoc");
    expect(restored?.adhocLabel).toBe("dentist");
  });

  it("carries an 'ignored' decision across, so a rebuild does not re-ask about it", async () => {
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(DWELL_THEN_WORK(), { publishEvents: false });
    const pending = (await listVisits({})).find((v) => v.status === "pending")!;
    await classifyVisit(pending.id, { action: "ignore" });

    await reprocessRange(new Date(T0));
    expect((await listVisits({})).some((v) => v.status === "ignored")).toBe(true);
  });

});

describe("healTrackingStateOnBoot", () => {
  it("does nothing on a brand new install", async () => {
    await expect(healTrackingStateOnBoot()).resolves.toBeNull();
  });

  it("leaves a clean history exactly as it was", async () => {
    // A boot after a clean shutdown must reproduce the same visits and
    // trips, not invent or drop any.
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(COMMUTE(), { publishEvents: false });

    const before = await snapshot();
    await healTrackingStateOnBoot();
    expect(await snapshot()).toEqual(before);
  });

  it("relinks a trip lost to a restart that happened mid-journey", async () => {
    // The failure it exists for: the in-memory link between one visit and
    // the next is dropped by a restart, leaving the next stop permanently
    // unconnected to wherever the device came from.
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);

    await processPositions([fix(HOME_LAT, 0), fix(45.01, 1), fix(45.02, 2)], { publishEvents: false });
    resetTrackingState(); // the restart: tripOrigin is gone
    await processPositions([fix(45.04, 4), fix(WORK_LAT, 5)], { publishEvents: false });

    expect(await listTrips({})).toHaveLength(0);

    await healTrackingStateOnBoot();
    expect(await listTrips({})).toHaveLength(1);
  });
});

describe("the raw fix log", () => {
  it("is never touched by a rebuild - it is what the rebuild reads from", async () => {
    place("Home", HOME_LAT);
    place("Work", WORK_LAT);
    await processPositions(COMMUTE(), { publishEvents: false });
    const before = db.select().from(positions).all().length;

    await reprocessRange(new Date(T0));
    expect(db.select().from(positions).all()).toHaveLength(before);
  });
});
